#!/bin/sh

package=$1

baseurl="https://aur.archlinux.org"
url="$baseurl/$package.git"
basedir=~/aur
packagedir="$basedir/$package"

function clone()
{
	echo "Clonning..."
	cd $basedir
	git clone $url
	echo "Clonning successful!"
}

function build()
{
	echo "Building..."
	cd $packagedir
	makepkg -sri
}


[[ -d "$packagedir" ]] || clone
[[ -f "$packagedir/PKGBUILD" ]] && build

echo "Content of $basedir/$package"
ls $packagedir
