#!/bin/sh
defaultOutput="eDP1"
[ ! -z $DEFAULT_OUTPUT ] && defaultOutput=$DEFAULT_OUTPUT 

outputs=$(xrandr | grep -v $defaultOutput | grep -e [^s]connected | awk '{print $1}')

for output in $outputs; do
	xrandr --output $output --auto --right-of $defaultOutput
	setwall
done
