#!/bin/bash
filename=$1
[ -z "$1" ] && filename="$(date +"%Y-%m-%dT%H-%M-%S").mp4"
geometry=$(slop -f "-video_size %wx%h -i :0.0+%x,%y")
ffmpeg \
    -framerate 30 \
    -f x11grab $geometry \
    -pix_fmt yuv420p \
    -preset slow \
    -crf 22 \
    -c:a aac \
    -vf "pad=ceil(iw/2)*2:ceil(ih/2)*2" \
    "$filename"
