#!/bin/sh
filename="$SCREENSHOT_DIR/$(date +"%Y-%m-%d_%H:%M:%S").png"

if [ "$1" = "-s" ]; then
	maim $@ $filename | xclip -selection clipboard -target image/png
else
	maim $filename -d 3
fi
notify-send 'Screenshot saved!' "$filename created" &

