#!/bin/sh
filename=~/Pictures/images/screenshots/$(date +"%Y-%m-%d_%H:%M:%S").png

if [ "$1" = "-s" ]; then
	maim $@ $filename | xclip -selection clipboard -target image/png
else
	maim $filename 
fi
notify-send 'Screenshot saved!' "$filename created" &

