#!/bin/bash

current_sink=$(currsink)
curr_volume=$($SCRIPTS_DIR/volume)
curr_volume=${curr_volume%%%}

if [[ ! -z "$(pgrep -x pulseaudio)" && -z "$(pgrep -x pipewire-pulse)" ]]; then
	up() {
		[ "$curr_volume" -gt 99 ] && exit 0;
		pactl set-sink-volume "$current_sink" +5%;
	}
	down() { pactl set-sink-volume "$current_sink" -5%; }
else
	up() { amixer set 'Master' 5%+; }
	down() { amixer set 'Master' 5%-; }
fi

case "$1" in
	up) up ;;
	down) down ;;
esac >/dev/null

notify-send "Sound $1" "Sound $1 by 5% to $curr_volume"
