#!/bin/sh
wifi_up=$($SCRIPTS_DIR/wifiup)

ip=$($SCRIPTS_DIR/ipaddr)
battery=$(acpi | awk '{print $4}' | sed "s/[A-z,:%]//g")
memory=$(free --si -h | grep Pam | awk '{print " "$3"/"$2}')
cpu=$(top -bn1 | grep "%CPU:" | sed "s/.*, *\([0-9.]*\)%* id.*/\1/" | awk '{print " "$2"%"}')
volume="奔 $($SCRIPTS_DIR/volume)";
touchpad_enabled="$($SCRIPTS_DIR/toen)"
plugged=$(acpi -a | grep on-line | wc -l)

case $((
	(battery < 10) 			* 1 +
	(battery >= 10 && battery < 20)	* 2 +
	(battery >= 20 && battery < 30)	* 3 +
	(battery >= 30 && battery < 40)	* 4 +
	(battery >= 40 && battery < 50)	* 5 +
	(battery >= 50 && battery < 60)	* 6 +
	(battery >= 60 && battery < 70)	* 7 +
	(battery >= 70 && battery < 80)	* 8 +
	(battery >= 80 && battery < 90)	* 9 +
	(battery >= 90)			* 10)) in
	(1) b_icon=;;
	(2) b_icon=;;
	(3) b_icon=;;
	(4) b_icon=;;
	(5) b_icon=;;
	(6) b_icon=;;
	(7) b_icon=;;
	(8) b_icon=;;
	(9) b_icon=;;
	(10) b_icon=;;
esac

if [[ $plugged -eq "1" ]]; then
	b_icon=""
fi

echo "$volume | $touchpad_enabled | $wifi_up $ip | $cpu | $memory | $b_icon $battery% |" $(date +"%H:%M %d/%m/%Y")

