#!/bin/sh

#mbsync mat1
#mbsync outlook

mail_dir=~/.local/share/mail

[ -d $mail_dir ] && mails=$(ls $mail_dir)

[ -z "$mails" ] && echo "$mail_dir does not exist, create the directory first" && exit 1

# Create links
for mail in $mails; do
	ls $mail_dir/$mail | while read dirname; do
	condition=$(echo "$mail_dir/$mail/$dirname" | grep 'Gmail' | wc -l)
 echo $dirname
	[ $condition -gt 0 ] && isGmail=1 || isGmail=0

	newdirname=$(echo $dirname | sed -e 's/\[Gmail\]\.//g' | tr "&" "+" | tr "," "/" | iconv -f UTF-7 -t UTF-8)

	[ ! -d "$newdirname" ] && [ "$isGmail" -eq 0 ] && symlink="$mail_dir/$mail/$newdirname" || symlink="$mail_dir/$mail/[Gmail].$newdirname"
	
	echo "$symlink"
	ln -s $mail_dir/$mail/$dirname $symlink 
		    
	done
done

