#!/bin/sh

if [[ "$1" -eq "" ]]; then
	echo Provide device id to be toggled
	read deviceid
else
	deviceid=$1
fi

exists=$(xinput list | grep pointer | awk -F'[=[]' '{print $2}'| grep $deviceid)

if [[ $exists -eq "" ]]; then
	echo "no such device"
	exit 1
fi

prop=$(xinput list-props $deviceid | grep Enabled | awk -F'[()]' '{print $2}')
enabled=$(xinput list-props $deviceid | grep Enabled | awk '{print $4}')

echo $prop
echo $enabled
if [[ "$enabled" -eq "1" ]]; then
	xinput set-prop $deviceid $prop 0
	echo "touchpad off"
else
	xinput set-prop $deviceid $prop 1
	echo "touchpad on"
fi
