#!/bin/bash

if [[ -n "$(pgrep -x pulseaudio)" || -n "$(pgrep -x pipewire-pulse)" ]]; then
	curr_volume=$(pactl list sinks |\
		grep '^[[:space:]]Poziom głośności:' |\
		head -n $(( $(currsink) +1 )) |\
		tail -n 1 |\
		sed -e 's,.* \([0-9][0-9]*\)%.*,\1,');
else
	curr_volume=$(awk -F"[][]" '/dB/' '{print $2}' <(amixer sget Master))
fi

echo "$curr_volume%"
