#!/bin/bash

if [[ -n "$(pgrep -x pulseaudio)" ]]; then
	current_sink=$(~/scripts/currsink);
	curr_volume=$(pactl list sinks | grep '^[[:space:]]Poziom głośności:' | head -n $(( $current_sink +1 )) | tail -n 1 | sed -e 's,.* \([0-9][0-9]*\)%.*,\1,');
else
	curr_volume=$(awk -F"[][]" '/dB/' {print $2} <(amixer sget Master))
fi

echo "$curr_volume%"
