#!/bin/sh

author=$1
url=$2
[ -z "$author" ] && echo "Missing author name" && exit 1
[ -z "$url"  ] && echo "Missing url" && exit 1

dir=~/music/podcasts/youtube/$author
mkdir -p $dir
cd $dir

echo "Downloading..."

youtube-dl -f bestaudio $url

echo "Preprocessing..."

find . -type f -iname "*.webm" -exec bash -c 'FILE="$1"; ffmpeg -i "${FILE}" -vn -ab 128k -ar 44100 -y "${FILE%.webm}.mp3";' _ '{}' \;
echo "Removing webm leftovers..."
rm *.webm*

echo "Done!"
