[colors.primary]
background = "#000000"

[font]
size = 13

[font.bold]
family = "JetBrains Mono"

[font.italic]
family = "Jetbrains Mono"

[font.normal]
family = "Jetbrains Mono"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Control|Shift"

[window]
opacity = 1
