[colors.primary]
background = "#000000"

[font]
size = 9

[font.bold]
family = "JetBrains Mono Nerd Font"

[font.italic]
family = "JetBrains Mono Nerd Font"

[font.normal]
family = "JetBrains Mono Nerd Font"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "J"
mods = "Control|Shift"

[window]
opacity = 0.9
